export const data = {
  list: [
    {
      entity: {
        id: 6,
        parentMenuId: 0,
        name: "categoryManage",
        icon: "el-icon-news",
        alias: "分类管理",
        state: "ENABLE",
        sort: 1,
        value: null,
        type: "NONE",
        discription: "用于分类管理的菜单",
        createUserId: 1,
      },
      childs: [
        {
          entity: {
            id: 7,
            parentMenuId: 6,
            name: "/categoryManage/categoryList",
            icon: "el-icon-user\r\n",
            alias: "分类中心",
            state: "ENABLE",
            sort: 0,
            value: "/categoryManage/categoryList",
            type: "NONE",
            discription: "用于文章分类管理的菜单",
            createUserId: 1,
          },
        },
      ],
    },
    {
      entity: {
        id: 9,
        parentMenuId: 0,
        name: "tagManage",
        icon: "el-icon-rank",
        alias: "标签管理",
        state: "ENABLE",
        sort: 2,
        value: null,
        type: "NONE",
        discription: "用于标签管理的菜单",
        createUserId: 1,
      },
      childs: [
        {
          entity: {
            id: 10,
            parentMenuId: 9,
            name: "/tagManage/tagList",
            icon: "el-icon-s-tools\n\r\n",
            alias: "标签中心",
            state: "ENABLE",
            sort: 0,
            value: "/tagManage/tagList",
            type: "NONE",
            discription: "标签中心",
            createUserId: 1,
          },
        },
      ],
    },
    {
      entity: {
        id: 21,
        parentMenuId: 0,
        name: "postManage",
        icon: "el-icon-news",
        alias: "文章管理",
        state: "ENABLE",
        sort: 1,
        value: null,
        type: "NONE",
        discription: "用于用户管理的菜单",
        createUserId: 1,
      },
      childs: [
        {
          entity: {
            id: 22,
            parentMenuId: 21,
            name: "/postManage/postList",
            icon: "el-icon-phone-outline\r\n",
            alias: "文章中心",
            state: "ENABLE",
            sort: 0,
            value: "/postManage/postList",
            type: "NONE",
            discription: "用于文章管理的菜单",
            createUserId: 1,
          },
        },
        {
          entity: {
            id: 36,
            parentMenuId: 21,
            name: "/postManage/deleteList",
            icon: "el-icon-phone-outline\r\n",
            alias: "回收站",
            state: "ENABLE",
            sort: 0,
            value: "/postManage/deleteList",
            type: "NONE",
            discription: "用于文章管理的菜单",
            createUserId: 1,
          },
        },
      ],
    },
    {
      entity: {
        id: 23,
        parentMenuId: 0,
        name: "commentManage",
        icon: "el-icon-news",
        alias: "评论管理",
        state: "ENABLE",
        sort: 1,
        value: null,
        type: "NONE",
        discription: "用于用户管理的菜单",
        createUserId: 1,
      },
      childs: [
        {
          entity: {
            id: 24,
            parentMenuId: 23,
            name: "/commentManage/commentList",
            icon: "el-icon-phone-outline\r\n",
            alias: "评论中心",
            state: "ENABLE",
            sort: 0,
            value: "/commentManage/commentList",
            type: "NONE",
            discription: "用于评论管理的菜单",
            createUserId: 1,
          },
        },
      ],
    },
    {
      entity: {
        id: 236,
        parentMenuId: 0,
        name: "loveManage",
        icon: "el-icon-news",
        alias: "喜欢管理",
        state: "ENABLE",
        sort: 1,
        value: null,
        type: "NONE",
        discription: "用于用户管理的菜单",
        createUserId: 1,
      },
      childs: [
        {
          entity: {
            id: 249,
            parentMenuId: 236,
            name: "/loveManage/loveList",
            icon: "el-icon-phone-outline\r\n",
            alias: "喜欢中心",
            state: "ENABLE",
            sort: 0,
            value: "/loveManage/loveList",
            type: "NONE",
            discription: "用于评论管理的菜单",
            createUserId: 1,
          },
        },
      ],
    },
  ],
};
